TABLES = {
    "users": {
        "columns": {
            "id": "BIGINT NOT NULL AUTO_INCREMENT",
            "email": "VARCHAR(255) NOT NULL",
            "password_hash": "VARCHAR(255) NULL",
            "name": "VARCHAR(100) NULL",
            "role": "VARCHAR(30) NOT NULL DEFAULT 'USER'",
            "status": "VARCHAR(30) NOT NULL DEFAULT 'active'",
            "email_verified_at": "DATETIME NULL",
            "last_login_at": "DATETIME NULL",
            "auth_provider": "VARCHAR(50) NULL",
            "oauth_id": "VARCHAR(255) NULL",
            "created_at": "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP",
            "updated_at": "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP",
        },
        "primary_key": ["id"],
        "unique_keys": {
            "uk_users_email": ["email"],
        },
        "indexes": {
            "idx_users_oauth": ["auth_provider", "oauth_id"],
        },
        "foreign_keys": {},
    },
    "user_profiles": {
        "columns": {
            "id": "BIGINT NOT NULL AUTO_INCREMENT",
            "user_id": "BIGINT NOT NULL",
            "phone_number": "VARCHAR(50) NULL",
            "birth_year": "SMALLINT NULL",
            "gender": "VARCHAR(20) NULL",
            "region_code": "VARCHAR(50) NULL",
            "region_name": "VARCHAR(100) NULL",
            "interests": "JSON NULL",
            "notification_email_enabled": "BOOLEAN NOT NULL DEFAULT TRUE",
            "created_at": "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP",
            "updated_at": "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP",
        },
        "primary_key": ["id"],
        "unique_keys": {
            "uk_user_profiles_user_id": ["user_id"],
        },
        "indexes": {
            "idx_user_profiles_region": ["region_code", "region_name"],
        },
        "foreign_keys": {
            "fk_user_profiles_user_id": {
                "columns": ["user_id"],
                "references": "users(id)",
                "on_delete": "CASCADE",
            },
        },
    },
    "company_profiles": {
        "columns": {
            "id": "BIGINT NOT NULL AUTO_INCREMENT",
            "user_id": "BIGINT NOT NULL",
            "company_name": "VARCHAR(255) NULL",
            "business_registration_no": "VARCHAR(50) NULL",
            "business_type": "VARCHAR(100) NULL",
            "region_code": "VARCHAR(50) NULL",
            "region_name": "VARCHAR(100) NULL",
            "industry_codes": "TEXT NULL",
            "industry_names": "TEXT NULL",
            "license_codes": "TEXT NULL",
            "license_names": "TEXT NULL",
            "is_youth_company": "BOOLEAN NOT NULL DEFAULT FALSE",
            "is_woman_company": "BOOLEAN NOT NULL DEFAULT FALSE",
            "is_disabled_company": "BOOLEAN NOT NULL DEFAULT FALSE",
            "is_verified": "BOOLEAN NOT NULL DEFAULT FALSE",
            "verification_status": "VARCHAR(30) NOT NULL DEFAULT 'UNVERIFIED'",
            "created_at": "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP",
            "updated_at": "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP",
        },
        "primary_key": ["id"],
        "unique_keys": {
            "uk_company_profiles_user_id": ["user_id"],
        },
        "indexes": {
            "idx_company_profiles_region": ["region_code", "region_name"],
            "idx_company_profiles_business_no": ["business_registration_no"],
        },
        "foreign_keys": {
            "fk_company_profiles_user_id": {
                "columns": ["user_id"],
                "references": "users(id)",
                "on_delete": "CASCADE",
            },
        },
    },
    "user_match_rules": {
        "columns": {
            "id": "BIGINT NOT NULL AUTO_INCREMENT",
            "user_id": "BIGINT NOT NULL",
            "rule_name": "VARCHAR(100) NULL",
            "keyword": "VARCHAR(255) NULL",
            "include_keywords": "TEXT NULL",
            "exclude_keywords": "TEXT NULL",
            "biz_types": "VARCHAR(255) NULL",
            "region": "VARCHAR(100) NULL",
            "regions": "TEXT NULL",
            "industry": "VARCHAR(100) NULL",
            "industries": "TEXT NULL",
            "organization": "VARCHAR(255) NULL",
            "organizations": "TEXT NULL",
            "product_class_nos": "TEXT NULL",
            "min_amount": "DECIMAL(18,2) NULL",
            "max_amount": "DECIMAL(18,2) NULL",
            "deadline_days": "INT NULL",
            "notification_enabled": "BOOLEAN NOT NULL DEFAULT TRUE",
            "is_active": "BOOLEAN NOT NULL DEFAULT TRUE",
            "created_at": "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP",
            "updated_at": "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP",
        },
        "primary_key": ["id"],
        "unique_keys": {},
        "indexes": {
            "idx_user_match_rules_user_id": ["user_id"],
            "idx_user_match_rules_active": ["is_active"],
            "idx_user_match_rules_user_active": ["user_id", "is_active"],
        },
        "foreign_keys": {
            "fk_user_match_rules_user_id": {
                "columns": ["user_id"],
                "references": "users(id)",
                "on_delete": "CASCADE",
            },
        },
    },
    "product_categories": {
        "columns": {
            "id": "BIGINT NOT NULL AUTO_INCREMENT",
            "source_type": "VARCHAR(30) NOT NULL DEFAULT 'PUBLIC_PROCUREMENT'",
            "product_class_no": "VARCHAR(100) NOT NULL",
            "category_depth_1": "VARCHAR(100) NOT NULL",
            "category_depth_2": "VARCHAR(100) NULL",
            "category_depth_3": "VARCHAR(100) NULL",
            "description": "TEXT NULL",
            "created_at": "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP",
            "updated_at": "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP",
        },
        "primary_key": ["id"],
        "unique_keys": {
            "uk_product_categories_source_class": ["source_type", "product_class_no"],
        },
        "indexes": {
            "idx_product_categories_depth_1": ["category_depth_1"],
            "idx_product_categories_depth_2": ["category_depth_2"],
            "idx_product_categories_depth_3": ["category_depth_3"],
        },
        "foreign_keys": {},
    },
    "bid_notices": {
        "columns": {
            "id": "BIGINT NOT NULL AUTO_INCREMENT",
            "notice_no": "VARCHAR(100) NOT NULL",
            "bid_notice_no": "VARCHAR(100) NULL",
            "bid_notice_ord": "VARCHAR(20) NOT NULL DEFAULT '000'",
            "biz_type": "VARCHAR(30) NOT NULL DEFAULT 'UNKNOWN'",
            "notice_type": "VARCHAR(50) NULL",
            "title": "VARCHAR(500) NOT NULL",
            "organization": "VARCHAR(255) NULL",
            "notice_org_code": "VARCHAR(50) NULL",
            "notice_org_name": "VARCHAR(255) NULL",
            "demand_org_code": "VARCHAR(50) NULL",
            "demand_org_name": "VARCHAR(255) NULL",
            "region": "VARCHAR(100) NULL",
            "region_code": "VARCHAR(50) NULL",
            "region_name": "VARCHAR(100) NULL",
            "industry_code": "VARCHAR(50) NULL",
            "industry_name": "VARCHAR(255) NULL",
            "eligible_industry_codes": "TEXT NULL",
            "eligible_industry_names": "TEXT NULL",
            "license_limit_items": "JSON NULL",
            "license_limit_raw_payload": "JSON NULL",
            "license_limit_result_code": "VARCHAR(20) NULL",
            "license_limit_result_message": "VARCHAR(255) NULL",
            "product_category_source_type": "VARCHAR(30) NOT NULL DEFAULT 'PUBLIC_PROCUREMENT'",
            "product_class_no": "VARCHAR(100) NULL",
            "product_name": "VARCHAR(255) NULL",
            "base_amount": "DECIMAL(18,2) NULL",
            "estimated_price": "DECIMAL(18,2) NULL",
            "budget_amount": "DECIMAL(18,2) NULL",
            "posted_at": "DATETIME NULL",
            "registered_at": "DATETIME NULL",
            "deadline_at": "DATETIME NULL",
            "opening_at": "DATETIME NULL",
            "status": "VARCHAR(30) NOT NULL DEFAULT 'OPEN'",
            "is_deadline_excluded": "BOOLEAN NOT NULL DEFAULT FALSE",
            "is_international": "BOOLEAN NOT NULL DEFAULT FALSE",
            "license_limit_text": "TEXT NULL",
            "match_keywords": "TEXT NULL",
            "source_url": "TEXT NULL",
            "detail_url": "TEXT NULL",
            "raw_payload": "JSON NULL",
            "last_synced_at": "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP",
            "collected_at": "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP",
            "created_at": "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP",
            "updated_at": "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP",
        },
        "primary_key": ["id"],
        "unique_keys": {
            "uk_bid_notices_notice_no": ["notice_no"],
            "uk_bid_notices_notice_ord_type": ["bid_notice_no", "bid_notice_ord", "biz_type"],
        },
        "indexes": {
            "idx_bid_notices_region": ["region"],
            "idx_bid_notices_organization": ["organization"],
            "idx_bid_notices_deadline_at": ["deadline_at"],
            "idx_bid_notices_biz_status_deadline": ["biz_type", "status", "deadline_at"],
            "idx_bid_notices_posted_at": ["posted_at"],
            "idx_bid_notices_registered_at": ["registered_at"],
            "idx_bid_notices_notice_org": ["notice_org_name"],
            "idx_bid_notices_demand_org": ["demand_org_name"],
            "idx_bid_notices_region_detail": ["region_code", "region_name"],
            "idx_bid_notices_industry": ["industry_code", "industry_name"],
            "idx_bid_notices_product": ["product_class_no", "product_name"],
            "idx_bid_notices_product_category": ["product_category_source_type", "product_class_no"],
            "idx_bid_notices_amount": ["estimated_price", "base_amount", "budget_amount"],
            "idx_bid_notices_sync": ["last_synced_at"],
        },
        "foreign_keys": {
            "fk_bid_notices_product_category": {
                "columns": ["product_category_source_type", "product_class_no"],
                "references": "product_categories(source_type, product_class_no)",
                "on_delete": "RESTRICT",
            },
        },
    },
    "match_results": {
        "columns": {
            "id": "BIGINT NOT NULL AUTO_INCREMENT",
            "bid_notice_id": "BIGINT NOT NULL",
            "user_match_rule_id": "BIGINT NOT NULL",
            "user_id": "BIGINT NULL",
            "match_score": "DECIMAL(5,2) NOT NULL DEFAULT 0",
            "match_status": "VARCHAR(30) NOT NULL DEFAULT 'MATCHED'",
            "matched_keywords": "TEXT NULL",
            "excluded_keywords": "TEXT NULL",
            "match_reason": "VARCHAR(500) NULL",
            "matched_at": "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP",
            "created_at": "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP",
            "updated_at": "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP",
        },
        "primary_key": ["id"],
        "unique_keys": {
            "uk_match_results_notice_rule": ["bid_notice_id", "user_match_rule_id"],
        },
        "indexes": {
            "idx_match_results_bid_notice_id": ["bid_notice_id"],
            "idx_match_results_rule_id": ["user_match_rule_id"],
            "idx_match_results_user_status": ["user_id", "match_status", "matched_at"],
        },
        "foreign_keys": {
            "fk_match_results_bid_notice_id": {
                "columns": ["bid_notice_id"],
                "references": "bid_notices(id)",
                "on_delete": "CASCADE",
            },
            "fk_match_results_rule_id": {
                "columns": ["user_match_rule_id"],
                "references": "user_match_rules(id)",
                "on_delete": "CASCADE",
            },
            "fk_match_results_user_id": {
                "columns": ["user_id"],
                "references": "users(id)",
                "on_delete": "CASCADE",
            },
        },
    },
    "email_notification_batches": {
        "columns": {
            "id": "BIGINT NOT NULL AUTO_INCREMENT",
            "user_id": "BIGINT NOT NULL",
            "subject": "VARCHAR(255) NULL",
            "total_count": "INT NOT NULL DEFAULT 0",
            "send_status": "VARCHAR(30) NOT NULL DEFAULT 'PENDING'",
            "scheduled_at": "DATETIME NULL",
            "sent_at": "DATETIME NULL",
            "error_message": "TEXT NULL",
            "created_at": "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP",
        },
        "primary_key": ["id"],
        "unique_keys": {},
        "indexes": {
            "idx_email_batches_user_status": ["user_id", "send_status"],
            "idx_email_batches_scheduled_at": ["scheduled_at"],
        },
        "foreign_keys": {
            "fk_email_batches_user_id": {
                "columns": ["user_id"],
                "references": "users(id)",
                "on_delete": "CASCADE",
            },
        },
    },
    "email_send_histories": {
        "columns": {
            "id": "BIGINT NOT NULL AUTO_INCREMENT",
            "user_id": "BIGINT NOT NULL",
            "match_result_id": "BIGINT NOT NULL",
            "email_batch_id": "BIGINT NULL",
            "recipient_email": "VARCHAR(255) NULL",
            "subject": "VARCHAR(255) NULL",
            "send_status": "VARCHAR(30) NOT NULL",
            "retry_count": "INT NOT NULL DEFAULT 0",
            "error_message": "TEXT NULL",
            "sent_at": "DATETIME NULL",
            "created_at": "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP",
        },
        "primary_key": ["id"],
        "unique_keys": {
            "uk_email_histories_user_match": ["user_id", "match_result_id"],
        },
        "indexes": {
            "idx_email_histories_user_id": ["user_id"],
            "idx_email_histories_match_result_id": ["match_result_id"],
            "idx_email_histories_batch_id": ["email_batch_id"],
            "idx_email_histories_send_status": ["send_status"],
        },
        "foreign_keys": {
            "fk_email_histories_user_id": {
                "columns": ["user_id"],
                "references": "users(id)",
                "on_delete": "CASCADE",
            },
            "fk_email_histories_match_result_id": {
                "columns": ["match_result_id"],
                "references": "match_results(id)",
                "on_delete": "CASCADE",
            },
            "fk_email_histories_batch_id": {
                "columns": ["email_batch_id"],
                "references": "email_notification_batches(id)",
                "on_delete": "SET NULL",
            },
        },
    },
    "collection_run_logs": {
        "columns": {
            "id": "BIGINT NOT NULL AUTO_INCREMENT",
            "job_name": "VARCHAR(100) NOT NULL",
            "status": "VARCHAR(30) NOT NULL",
            "started_at": "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP",
            "ended_at": "DATETIME NULL",
            "query_from": "DATETIME NULL",
            "query_to": "DATETIME NULL",
            "fetched_count": "INT NOT NULL DEFAULT 0",
            "saved_count": "INT NOT NULL DEFAULT 0",
            "skipped_count": "INT NOT NULL DEFAULT 0",
            "error_count": "INT NOT NULL DEFAULT 0",
            "error_message": "TEXT NULL",
            "metadata": "JSON NULL",
        },
        "primary_key": ["id"],
        "unique_keys": {},
        "indexes": {
            "idx_collection_run_logs_job_started": ["job_name", "started_at"],
            "idx_collection_run_logs_status": ["status"],
        },
        "foreign_keys": {},
    },
    "license_backfill_logs": {
        "columns": {
            "id": "BIGINT NOT NULL AUTO_INCREMENT",
            "status": "VARCHAR(30) NOT NULL",
            "started_at": "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP",
            "ended_at": "DATETIME NULL",
            "target_count": "INT NOT NULL DEFAULT 0",
            "enriched_count": "INT NOT NULL DEFAULT 0",
            "no_data_count": "INT NOT NULL DEFAULT 0",
            "error_count": "INT NOT NULL DEFAULT 0",
            "sample_errors": "JSON NULL",
        },
        "primary_key": ["id"],
        "unique_keys": {},
        "indexes": {
            "idx_license_backfill_logs_started": ["started_at"],
            "idx_license_backfill_logs_status": ["status"],
        },
        "foreign_keys": {},
    },
    "user_search_histories": {
        "columns": {
            "id": "BIGINT NOT NULL AUTO_INCREMENT",
            "user_id": "BIGINT NOT NULL",
            "keyword": "VARCHAR(255) NULL",
            "filters": "JSON NULL",
            "result_count": "INT NOT NULL DEFAULT 0",
            "searched_at": "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP",
        },
        "primary_key": ["id"],
        "unique_keys": {},
        "indexes": {
            "idx_user_search_histories_user_time": ["user_id", "searched_at"],
            "idx_user_search_histories_keyword": ["keyword"],
        },
        "foreign_keys": {
            "fk_user_search_histories_user_id": {
                "columns": ["user_id"],
                "references": "users(id)",
                "on_delete": "CASCADE",
            },
        },
    },
    "saved_bid_notices": {
        "columns": {
            "id": "BIGINT NOT NULL AUTO_INCREMENT",
            "user_id": "BIGINT NOT NULL",
            "bid_notice_id": "BIGINT NOT NULL",
            "memo": "VARCHAR(500) NULL",
            "created_at": "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP",
        },
        "primary_key": ["id"],
        "unique_keys": {
            "uk_saved_bid_notices_user_notice": ["user_id", "bid_notice_id"],
        },
        "indexes": {
            "idx_saved_bid_notices_user_id": ["user_id"],
            "idx_saved_bid_notices_notice_id": ["bid_notice_id"],
        },
        "foreign_keys": {
            "fk_saved_bid_notices_user_id": {
                "columns": ["user_id"],
                "references": "users(id)",
                "on_delete": "CASCADE",
            },
            "fk_saved_bid_notices_notice_id": {
                "columns": ["bid_notice_id"],
                "references": "bid_notices(id)",
                "on_delete": "CASCADE",
            },
        },
    },
    "user_consents": {
        "columns": {
            "id": "BIGINT NOT NULL AUTO_INCREMENT",
            "user_id": "BIGINT NOT NULL",
            "consent_type": "VARCHAR(50) NOT NULL",
            "is_agreed": "BOOLEAN NOT NULL DEFAULT FALSE",
            "agreed_at": "DATETIME NULL",
            "revoked_at": "DATETIME NULL",
        },
        "primary_key": ["id"],
        "unique_keys": {
            "uk_user_consents_user_type": ["user_id", "consent_type"],
        },
        "indexes": {
            "idx_user_consents_user_id": ["user_id"],
        },
        "foreign_keys": {
            "fk_user_consents_user_id": {
                "columns": ["user_id"],
                "references": "users(id)",
                "on_delete": "CASCADE",
            },
        },
    },
    "admin_announcements": {
        "columns": {
            "id": "BIGINT NOT NULL AUTO_INCREMENT",
            "title": "VARCHAR(255) NOT NULL",
            "content": "TEXT NULL",
            "is_visible": "BOOLEAN NOT NULL DEFAULT TRUE",
            "created_by": "BIGINT NULL",
            "created_at": "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP",
            "updated_at": "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP",
        },
        "primary_key": ["id"],
        "unique_keys": {},
        "indexes": {
            "idx_admin_announcements_visible": ["is_visible"],
            "idx_admin_announcements_created_by": ["created_by"],
        },
        "foreign_keys": {
            "fk_admin_announcements_created_by": {
                "columns": ["created_by"],
                "references": "users(id)",
                "on_delete": "SET NULL",
            },
        },
    },
    "app_notifications": {
        "columns": {
            "id": "BIGINT NOT NULL AUTO_INCREMENT",
            "user_id": "BIGINT NOT NULL",
            "title": "VARCHAR(255) NOT NULL",
            "message": "TEXT NOT NULL",
            "bid_notice_id": "BIGINT NULL",
            "is_read": "BOOLEAN NOT NULL DEFAULT FALSE",
            "created_at": "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP",
        },
        "primary_key": ["id"],
        "unique_keys": {},
        "indexes": {
            "idx_app_notifications_user_id": ["user_id"],
        },
        "foreign_keys": {
            "fk_app_notifications_user_id": {
                "columns": ["user_id"],
                "references": "users(id)",
                "on_delete": "CASCADE",
            },
        },
    },
}
